//AUTH
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

//LISTS
export const GET_LISTS_SUCCESS = "GET_LISTS_SUCCESS";
export const GET_LISTS_FAIL = "GET_LISTS_FAIL";
export const ADD_LIST_FAIL = "ADD_LIST_FAIL";
export const UPDATE_LIST_COUNT = "UPDATE_LIST_COUNT";
export const STOPPED_LISTENING_LISTS = "STOPPED_LISTENING_LISTS";
export const SHARE_LIST_FAIL = "SHARE_LIST_FAIL";
export const SHARE_LIST_SUCCESS = "SHARE_LIST_SUCCESS";
export const CLEAR_SHARE_ERROR = "CLEAR_SHARE_ERROR";

//ITEMS
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAIL = "GET_ITEMS_FAIL";
export const TOGGLE_ITEM_SUCCESS = "TOGGLE_ITEM_SUCCESS";
export const TOGGLE_ITEM_FAIL = "TOGGLE_ITEM_FAIL";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";
export const ADD_ITEMS_FAIL = "ADD_ITEMS_FAIL";
export const EDIT_ITEM_SUCCESS = "EDIT_ITEM_SUCCESS";
export const EDIT_ITEM_FAIL = "EDIT_ITEM_FAIL";
export const CLEAR_GOT_ITEMS_FAIL = "CLEAR_GOT_ITEMS_FAIL";
export const STOPPED_LISTENING_ITEMS = "STOPPED_LISTENING_ITEMS";
